//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.16 at 11:18:52 AM GMT 
//


package com.jpmc.rdt.docmgmt.excel.loader.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sheetColumn">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="dataType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dbColumn">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="dataType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="size" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="defaultValue" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sheetColumn",
    "dbColumn"
})
public class Mapping {

    @XmlElement(required = true)
    protected SheetColumn sheetColumn;
    @XmlElement(required = true)
    protected DbColumn dbColumn;

    /**
     * Gets the value of the sheetColumn property.
     * 
     * @return
     *     possible object is
     *     {@link SheetColumn }
     *     
     */
    public SheetColumn getSheetColumn() {
        return sheetColumn;
    }

    /**
     * Sets the value of the sheetColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link SheetColumn }
     *     
     */
    public void setSheetColumn(SheetColumn value) {
        this.sheetColumn = value;
    }

    /**
     * Gets the value of the dbColumn property.
     * 
     * @return
     *     possible object is
     *     {@link DbColumn }
     *     
     */
    public DbColumn getDbColumn() {
        return dbColumn;
    }

    /**
     * Sets the value of the dbColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbColumn }
     *     
     */
    public void setDbColumn(DbColumn value) {
        this.dbColumn = value;
    }

}
